### ISSUE TITLE
Specify that only one rule can be filtered for in automatic reports

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-documentation#1048]
Hi team,

It seems we can only configure one rule for each automatic daily report, is that the expected behavior? If so, it should be specified in the following reference: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/reports.html

Regards,
Sergio.

**Comment by JaoChaos** [comment]
Indeed, if you create a section `<reports></reports>`, inside you can only put one rule, one title, etc. Why? Because what we want is to generate a specific report. For example:

If we want a report for rule 700, we write:

<reports>
   <rule>700</rule>
   <title>Report rule 700</title>
    ...
</reports>

And we would have a report with what the 700 rule has done today on all machines, or if you specify an IP then only on that machine, etc.

The cool thing is that we can create as many sections `<reports></reports>` as we need, so we can give a rule to every section and have a report for every rule.
That's why reports only accept one variable from each option, because you can have multiple reports.

However, I'm going to improve that section in the documentation based on the fact that the confusion you've had, anyone can have it.

I hope to have clarified this issue a little and thank you very much for opening the issue :+1:
