### ISSUE TITLE
email alert by rule id

### ISSUE THREAD

**Issue by nikhilsingh42** [wazuh/wazuh-documentation#1091]
Hi,

I have configured email alert by rule id 
![image](https://user-images.githubusercontent.com/47519186/55143826-92537300-5165-11e9-8962-6596d7984450.png)

I am getting the log in kibana discover with these rule but not the email alerts.
It should forward the email alert irrespective of rule level?

Thanks & Regards
Nikhil Singh

**Comment by jesusgn90** [comment]
Hello @nikhilsingh42,

Sorry about the problems you are facing with e-mail reports. Have you followed [our guide](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html) where we explain how to properly configure it?

Just to be sure your e-mail server is working properly, can you please check if your server can send emails?

```
# echo "Test mail from postfix" | mail -s "Test Postfix" -r "you@example.com" you@example.com
```

You should receive an email at you@example.com. Replace "you" and "example" with your own e-mail.

We have an option to force the e-mail being sent using [alert_by_email](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html#force-forwarding-an-alert-by-email) which means you can tune your rules so they will be sent always.

Just to be sure, have you configured your e-mail server so it can send e-mails properly? We explain how to [here](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/smtp_authentication.html)

It would be nice too if you share the `<global>` section from the `ossec.conf` file of your Wazuh manager, it should look like something similar to this:

```
    <global>
        <email_notification>yes</email_notification>
        <email_to>me@test.com</email_to>
        <smtp_server>mail.test.com..</smtp_server>
        <email_from>wazuh@test.com</email_from>
    </global>
```

I'll wait for your response, we can help here.

Best regards,
Jesús

**Comment by nikhilsingh42** [comment]
Hi ,

I am receiving the email alerts there is no issue with that.
But in the screen shot shared i have configured the email alert by rule id .
But for these rule id i am not getting any email alert.
![image](https://user-images.githubusercontent.com/47519186/55226253-8ab1ce00-523a-11e9-87a4-9fe68ca152e5.png)

Thanks & regards
Nikhil Singh

**Comment by jesusgn90** [comment]
Hello again @nikhilsingh42,

Now that we know your mail server is properly sending emails and we know you are receiving some alerts, it's time to debug about the rest of the alerts.

**Level 0 rules**

Rules with level 0 won't be sent. That level is commonly used to create child rules, so one or more rules are used if the parent rule is fired. Some of your rules are probably using a level 0 definition.

Example (`id="530"`):

```
grep -R '"530"' /var/ossec/ruleset/
/var/ossec/ruleset/rules/0015-ossec_rules.xml:  <rule id="530" level="0">
```

For more information about rule levels, please check [our guide](https://documentation.wazuh.com/current/user-manual/ruleset/rules-classification.html).

**Minimum rule level configuration**

In your `ossec.conf` file you should see a block like this:

```xml
<alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
</alerts>
```

As you can see, `<email_alert_level>12</email_alert_level>` is the minimum rule level that the rule must use in order to send alerts from that rule. More information can be found [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html?highlight=alerts#email-alert-level).

You have two options here:

a) Reduce the `email_alert_level` to something lower, example: `<email_alert_level>7</email_alert_level>` 
b) Customize certain rules so you can avoid an email overflow, locate the desired rule, then add the next option to force that rule even if it's level is lower than your `email_alert_level`. 

Here we have an example rule (extracted from `/var/ossec/ruleset/rules/0015-ossec_rules.xml`) that won't be sent if the `email_alert_level` is 12:

```xml
<rule id="533" level="7">
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat listening ports</match>
    <check_diff />
    <description>Listened ports status (netstat) changed (new port opened or closed).</description>
    <group>pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
</rule>
```
If we want to keep our minimum level at 12 but bypass this restriction for that rule, just add this line:

```xml
<options>alert_by_email</options>
```

So your rule should look like this:

```xml
<rule id="533" level="7">
    <options>alert_by_email</options>
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat listening ports</match>
    <check_diff />
    <description>Listened ports status (netstat) changed (new port opened or closed).</description>
    <group>pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
</rule>
```
You can read more about our ruleset and how to customize it [here](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html). 

**Finding rules that inherit from a level 0 rule**

As we discussed, you should replace your level 0 rules from the email configuration, here is how to find associated rules:

Let's find the rules that inherit from rule "530" which is a level 0 rule.

```
grep -R '<if_sid>530</if_sid>' /var/ossec/ruleset/ -B4 | grep 'id='
/var/ossec/ruleset/rules/0015-ossec_rules.xml-  <rule id="531" level="7" ignore="7200">
/var/ossec/ruleset/rules/0015-ossec_rules.xml-  <rule id="533" level="7">
/var/ossec/ruleset/rules/0015-ossec_rules.xml-  <rule id="534" level="1">
/var/ossec/ruleset/rules/0015-ossec_rules.xml-  <rule id="535" level="1">
/var/ossec/ruleset/rules/0340-puppet_rules.xml-    <rule id="80090" level="0">
```

As we can see, there are 5 rules that inherit from rule "530", note that a child rule might be a parent rule too. From the above output, you can take the rule IDs for your email configuration. You can use the same logic as before for the rest of the level 0 rules.

Once you are done, remember to restart the service as follow:

```
systemctl restart wazuh-manager
```

I hope it helps.

Ask us if you are still in need of help.

In addition, we have [Slack community channel](https://wazuh.com/community/join-us-on-slack/) and [Google mailing list](https://groups.google.com/d/forum/wazuh) where we can help you too.

Kind regards,
Jesús

**Comment by jesusgn90** [comment]
Hello again @nikhilsingh42,

From https://github.com/wazuh/wazuh-documentation/issues/1110 I understand this ticket was solved by our last suggestions so I'm going to close this ticket.

Remember that you can reopen or create new tickets as much as you need.

Best regards,
Jesús
