### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by niravradia** [wazuh/wazuh-documentation#114]
There isn't much documented regarding what should be the recommended hardware(RAM, CPU cores, Disk size) setup for Wazuh server and Elasticsearch nodes. This can include recommendations based on number of machines which needs to be monitored.

**Comment by PSanchezR** [comment]
Hello Niravradia,

We are currently working on a document with the minimum and recommended requirements for the optimal operation of agents, managers and ELK servers. The document will be available soon in the official documentation of Wazuh.

If you have any other questions, I will be happy to help you.

Thank you for your feedback.

Regards,
Pablo.

**Comment by chaputj** [comment]
Hello! Is the document ready now ?
Do you have some guidelines for 100 agents, 1000, 2000 agents and more ?

I'm planing to deploy more agents soon.

**Comment by jesuslinares** [comment]
Hi @chaputj ,

The documentation is not ready yet. 

The hardware requirements don't depend on the number of agents, it depends on the EPS (event per second). Usually, Windows agents generate more event than Linux, but if you are using Audit in Linux, it may be very noisy.

**Comment by jesuslinares** [comment]
Hi @chaputj ,

The documentation is not ready yet.

The hardware requirements don't depend on the number of agents, it depends on the EPS (event per second). Usually, Windows agents generate more event than Linux, but if you are using Audit in Linux, it may be very noisy.

For Wazuh managers, we recommend scaling horizontally: https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html.

Regarding Elasticsearch, a "safe way" to proceed is to create a scalable architecture with 3 master + 3 data nodes. It is really easy to add data nodes until the performance is good enough. The disk (SSD) is a key factor for performance. On the other hand, in small environments, 3 master/data nodes will be enough.

Let me know if you need more help. Also, you can share it in the [wazuh-list](https://groups.google.com/forum/#!forum/wazuh).

Thanks,
Jesus.

**Comment by chaputj** [comment]
I'm using SSD drives. Thanks

How can I figure out my current EPS ?

By adding new agents, how can I figure out my max acceptable EPS on my Wazuh Manager according to the actual VM specs ?

**Comment by jesuslinares** [comment]
Hi @chaputj ,

You can see the events that an agent is sending to the manager in the file:

> /var/ossec/var/run/ossec-agentd.state

```
# cat ossec-agentd.state
# State file for ossec-agentd

# Agent status:
# - pending:      waiting for get connected.
# - connected:    connection established with manager in the last 60 seconds.
# - disconnected: connection lost or no ACK received in the last 60 seconds.
status='pending'

# Last time a keepalive was sent
last_keepalive=''

# Last time a control message was received
last_ack=''

# Number of generated events
msg_count='0'

# Number of messages (events + control messages) sent to the manager
msg_sent='3'
```

Using the _msg_count_, you can estimate the number of events that you are sending to the manager: _average of msg_count_ * _number of agents_.

Since Wazuh v3.2.4, if you see the following logs, it means that the manager is overloaded:

> 2018/06/05 15:03:03 ossec-remoted: WARNING: Message queue is full (262144). Events may be lost.
> 2018/06/05 16:15:59 ossec-analysisd: WARNING: Input buffer is full (1500000). Events may be lost.

So, it is not able to handle the current EPS and you should increase the hardware requirements or scale horizontally (cluster).

Regarding the hardware for the managers, we recommend faster CPUs instead of more cores. 8GB of RAM is enough for the most of the cases and the best SSD that you can afford.

We are currently working on a tool to get useful metrics and be able to estimate the EPS and the hardware required. In addition, we are improving remoted and analysisd to run in several threads, take advantage of the multicore processors.

**Comment by chaputj** [comment]
Thank you!
