### ISSUE TITLE
Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.

### ISSUE THREAD

**Issue by begize** [wazuh/wazuh-documentation#127]
os:centos 7 64bit
i install kibana by Installation guide ,server is running,but dashboard show error for "plugin:elasticsearch@6.1.0",how to fix it?

![image](https://user-images.githubusercontent.com/26645073/34150686-0ccc9a52-e4e4-11e7-97cb-5a19e01e0478.png)

![image](https://user-images.githubusercontent.com/26645073/34150622-e0d72b9c-e4e3-11e7-9727-d20b899df3f7.png)

**Comment by JuanjiJG** [comment]
Hi @begize, sorry for the late response.

This problems is usually associated with an upgrade of the Elastic Stack, but if you didn't make an upgrade, it may be also a problem during the installation process. You can follow these steps in order to get it working again. Please execute the commands as **superuser**:

1. **Stop Kibana and Logstash**:
`systemctl stop kibana`
`systemctl stop logstash`

2. **Delete the Kibana and Wazuh App configuration files** (**Warning**: this commands will delete all the configuration, custom visualizations and index-patterns from your Kibana installation):
`curl -XDELETE localhost:9200/.kibana`
`curl -XDELETE localhost:9200/.wazuh`
`curl -XDELETE localhost:9200/.wazuh-version`

3. **Start again Kibana and Logstash**:
`systemctl start logstash`
`systemctl start kibana`

Now you can access again the Kibana webpage and everything should work again as expected. Please let me know if the problem still persists, or if you have more questions, doubts or problems about anything.

Best regards,
Juanjo

**Comment by begize** [comment]
hi Juanjo:
fix problem after these steps ,thank you very much ~~~

**Comment by JuanjiJG** [comment]
You're welcome @begize! Glad to hear that everything works fine now! I'll proceed to close this issue.

Best regards,
Juanjo
