### ISSUE TITLE
Kibana plugin installation instruction should offer a way to install the right version

### ISSUE THREAD

**Issue by jsoref** [wazuh/wazuh-documentation#1295]
I'm running kibana 6.8.0. The docs for wazuh assume I'm using 7.1.1, which is frustrating.

I can install the version I need using:
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.2_6.8.0.zip
```

It would be nice if the instructions were something like:
```
KIBANA_VERSION=$(/usr/share/kibana/bin/kibana --version 2>/dev/null)
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.2_${KIBANA_VERSION}.zip
```

**Comment by juankaromo** [comment]
Hi @jsoref 

The command to install the app you are indicating belongs to the master branch. The master branch has the latest (and not yet released) changes of Wazuh's app, and to this day, it is version `3.9.2-7.1.1`.

You can find more information about the Wazuh app branches and tags (which are the versions of the branches where we have made a release) here https://github.com/wazuh/wazuh-kibana-app/wiki/About-our-branches-and-tags

For your specific case, and seeing that you need a version of Wazuh compatible with the Elastic Stack 6.8.0, I recommend that you select a branch of the app that is compatible with it.

To do this click on the branch selector, go to the tags tab, and look for the compatible branch, in this case `3.9.2-6.8.0`. 

![image](https://user-images.githubusercontent.com/21195730/60014619-b4379580-9681-11e9-8eaf-4af154a3c845.png)

Once selected, the instruction to install the app will be customized for the selected version.

Hope this helps.

Regards,

**Comment by jsoref** [comment]
That is not remotely helpful.

No sane system would require a user to do this.

What I'm suggesting is a single command that would "just work" in general, and can you're a friendly error when the plug-in isn't available.

**Comment by jesusgn90** [comment]
Hi @jsoref ,

> That is not remotely helpful.

Sorry about hearing that, we try to provide easy docs for our users and maybe the @juankaromo was not helpful at all, we'll try to improve the way our docs tell you how to install our plugin.

> No sane system would require a user to do this.

Yes, you are right and that's something we want to avoid.

> What I'm suggesting is a single command that would "just work" in general

The command won't work always, that's why we are not using it, but as I said, we'll review that section taking care of our community's feedback such as your comment, really appreciated.

> and can yield a friendly error when the plug-in isn't available.

That's not as easy as changing a message. Kibana is not being developed by our team, it's a third party software so there is no way to change by ourselves.

@jsoref let us know if you need any kind of help, in addition to this repository we are also on [Slack](https://wazuh.com/community/join-us-on-slack/) and [Google forum](https://groups.google.com/forum/#!forum/wazuh), feel free to join them.

Best regards,
Jesús

**Comment by alberpilot** [comment]
I proceed to close this issue. @jsoref please, don't hesitate to re-open if necessary. 

Regards, 
Alberto R
