### ISSUE TITLE
how can i connect modsecurity in wazuh?

### ISSUE THREAD

**Issue by sasam3l4** [wazuh/wazuh-documentation#1341]

**Comment by Zenidd** [comment]
Hi @sasam3l4,

To analyze the events generated by `ModSecurity` you have to create a configuration `<localfile>` block on `/var/ossec/etc/ossec.conf` . With this configuration block, `Wazuh` is able to read the events from the `ModSecurity` log and trigger alerts based on these events.

The block below is included in the default configuration. You need to fill the <location> tag with the path to your ModSecurity log files. There is more than one log file so if you want to monitor them all you will have to create a block <localfile> for each one. The main log file on ModSecurity is error.log:
```
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/error.log</location>
  </localfile>
```

Our ruleset has rules and decoders useful to analyze ModSecurity events.

Please, let me know if it helps. 

Greetings, Juan Pablo Sáez

**Comment by sasam3l4** [comment]
hi @Zenidd 

Do i have to install an agent to the modsecurity too right? 

regards,
samela

**Comment by Zenidd** [comment]
Hi again @sasam3l4,

Please, give me more details about your use case so that I can advise you accurately.

Assuming you have a machine with the manager installed and you have another machine with the ModSecurity firewall that you want to monitor, I can think of two approaches:

- [Install Wazuh's agent](https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-agent/index.html) This option is the one I recommend since you can keep an exhaustive control of what happens on the machine, not just ModSecurity.

- Forward the ModSecurity logs to Wazuh manager using [Rsyslog](https://www.rsyslog.com/) or similar software.

As i said, the more information you give me about your use case the more I can customize the solution for you!

Please let me know if it helps.

Best regards, Juan Pablo Sáez

**Comment by sasam3l4** [comment]
Hi @Zenidd 

>  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/error.log</location>
  </localfile>

I tried to input this in ossec.conf but there was an error 

>Error Validating XML

**Comment by sasam3l4** [comment]
Hi @Zenidd 
I have a Ubuntu machine for wazuh-manger also I have another machine for modsecurity.
Sorry for the late notice.

regards,
samela

**Comment by Zenidd** [comment]
Hi again @sasam3l4,

The most recommended option is to [install the Wazuh agent](https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-agent/index.html) on your ModSecurity machine. 

After installation, please try to add the following block to the `/var/ossec/etc/ossec.conf` file of the agent. 

Please let me know how it goes. 

Greetings, Juan Pablo Sáez

**Comment by sasam3l4** [comment]
Hi @Zenidd 
Sorry for the late notice, Thank you for your guidance I finally got the logs from modsecurity and display it in wazuh.

Thank you again,
samela

**Comment by Zenidd** [comment]
Hi @sasam3l4,

I'm glad you managed to configure Wazuh according to your needs!

I'm closing this ticket, if we can help you with any other configuration or problem you may have, do not hesitate to reopen this ticket or open a new one. You can also contact us through our [slack channel](https://wazuh.com/community/join-us-on-slack/) and our [mailing list](https://groups.google.com/forum/#!forum/wazuh). 

Kind regards, Juan Pablo Sáez

**Comment by vncloudsco** [comment]
@Zenidd  
I posted a configuration problem as above please help me. thank you very much.

https://github.com/wazuh/wazuh-documentation/issues/3011

**Comment by mr-money-software** [comment]
@Zenidd is this still valid?
I am trying to connect the Wazuh-Agent, but the tested modsecurity reports are not getting listed within the dashboard.

**added the following paths:**
```
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/error.log</location>
  </localfile>

  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/error_*.log</location>
  </localfile>
```

Then restarted wazuh-agent and started a test via nikto.

https://wazuh.com/blog/analyzing-modsecurity-events-with-wazuh/
**example:**
```
[Sun Nov 17 13:03:46.515736 2024] [:error] [pid 299960:tid 139701839185472] [client .....:59678] [client ....] ModSecurity: Warning. Matched phrase "nikto" at REQUEST_HEADERS:User-Agent. [file "/etc/crs4/rules/REQUEST-913-SCANNER-DETECTION.conf"] [line "56"] [id "913100"] [msg "Found User-Agent associated with security scanner"] [data "Matched Data: nikto found within REQUEST_HEADERS:User-Agent: Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (Test:006605)"] [severity "CRITICAL"] [ver "OWASP_CRS/4.0.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation-scanner"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/224/541/310"] [tag "PCI/6.5.10"] [hostname "tobias.h2.mister-money.de"] [uri "/mobileadmin/logs/"] [unique_id "ZznpsvrtuS9zoHgyYSHLlwAAAEQ"]
```

But this is not getting registered or reported within wazuh threat hunting.
The log is getting hundreds of ModSecurity records.
Could it be that it is due to the “DetectionOnly” mode?

This is what I had expected, I also tried to filter via data.id is ModSecurity, but not a single report.

Example images of what I had expected:

![The-scanning-activity-of-Nikto-triggered-several-alerts-on-ModSecurity-2](https://github.com/user-attachments/assets/04df11bd-6e6a-490b-a64d-d6f564c60103)

![Wazuh-dashboard-02](https://github.com/user-attachments/assets/ee3f0878-d8c4-4c63-965b-09c78bc132ba)

But not a single Nikto Request is getting listed.
