### ISSUE TITLE
Roadmap for Wazuh 

### ISSUE THREAD

**Issue by esfateev** [wazuh/wazuh-documentation#1398]
Hi!
Is it possible to prepare somewhere a roadmap for major wazuh updates? 
I propose to publish roadmap on official site like this -> https://www.zabbix.com/roadmap

BR, Eugene

**Comment by Zenidd** [comment]
Hi @esfateev,

To date, Wazuh roadmap is defined by its Github projects:

- [v3.9.4 project](https://github.com/wazuh/wazuh/projects/37)
- [v3.10 project](https://github.com/wazuh/wazuh/projects/30)
- [v.3.11 project](https://github.com/wazuh/wazuh/projects/32)

We are also planning to do roadmap issues, such as https://github.com/wazuh/wazuh/issues/3709 to document a more in-depth explanation about the objectives and how much of them we have achieved.

On the other hand, broadly speaking, this is our short to medium term roadmap:

- Improve container monitoring.
- Improve cloud monitoring.
- LDAP monitoring.
- VMWare monitoring.
- Kafka subs/provider.
- Status vs Alerts.
- Wazuh plugins.
- Yara.

and more..

I'm also happy to announce that we are about to release 3.9.4 (in the next few days)!

I hope it helps. Greetings, 
Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi again @esfateev,

I'm closing this ticket due to inactivity. If you need more information about our roadmap or any other topic, don't hesitate to open a new ticket or reopen this. 

On the other hand, if you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack. 

We will happy to help you in the Community channel.

Greetings, Juan Pablo Sáez
