### ISSUE TITLE
Minor typo in syscollector wodle documentation

### ISSUE THREAD

**Issue by K-Embee** [wazuh/wazuh-documentation#2353]
The section, referring to the hotfixes option, `This option is enabled by default but no included in the initial configuration.` is misspelt (`no` -> `not`)

Documentation link: https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/wodle-syscollector.html#hotfixes

**Comment by s-ocando** [comment]
Included the fixed in the missing branches: [4.2](https://github.com/wazuh/wazuh-documentation/commit/94cadfdda76e1ab66caa8c846e5eebe6a190be85), [4.1](https://github.com/wazuh/wazuh-documentation/commit/34b39e412a35aba3489a6ba0baaa16ff4b3cfab3), [4.0](https://github.com/wazuh/wazuh-documentation/commit/7f4d794bbff674ab6e34d4afd9533509f2638f59) and [3.13](https://github.com/wazuh/wazuh-documentation/commit/dc516b679c63d1d8ea7cd702572ff802600bd6a5).
