### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by genesis32** [wazuh/wazuh-documentation#27]
Just want some feedback on a few changes that I've put here.

[Ideas for new template](https://github.com/wazuh/wazuh-documentation/compare/new_template...genesis32:new_template?expand=1)

1. Include specific instructions for each OS you support w/ packages. (Which are those?)
2. Add curl commands to test functionality
3. File creations & initial contents should be easily executable via the command line.
4. Maybe build out installation instructions for each type of machine? manager, agent, api, elastic+kibana? If we build out more comprehensive instructions it might be a good idea to break them out into their own documentation.

**Comment by snaow** [comment]
Hi @genesis32,

Thanks so much for sharing your ideas, please feel free to send a PR directly to the repo:branch.

1. Agree, on final version for this documentation, we will explain in detail how to install it in different OS, including dependencies and requirements.
Also, as you notice, we want to improve the process of adding the repository for Debian/Ubuntu packages, so the final user does not have to fill manually the distro/version.
We are thinking about creating an automatic sh/bash to pipe it and install the repositories, like Node or other software does. For example

```
curl -sL https://packages.wazuh.com/setup | sudo -E bash -
sudo apt-get install wazuh-manager && sudo apt-get install wazuh-api
``` 

2. Totally agree.
3. Exactly, on our current documentation we are doing that way, we will upload the conf's files so users should be able to import/load/copy the files just downloading them with curl.
4. We want to keep it simple, we can break them out into different pieces for detailed explaining but in the end we would like to create an easy and useful guide for deploying Wazuh, the software is highly customizable (OSSEC, Elastic, OpenSCAP, API, Kibana..) but for the first installation we should keep everything simple in order to perform an easy installation.


Thanks so much again for your feedback, we are happy to listen to you guys and keep doing our best to improve everything.

Regards,

Pedro.

**Comment by jesuslinares** [comment]
I close the issue because I think the current documentation covers all these aspects. Feel free to open it again if you have more recommendations.

Thanks a lot for your feedback.
