### ISSUE TITLE
Update Docker documentation

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#2845]
Hello team,

As the full Wazuh Docker stack has been fully reworked and also the next release involves several breaking changes, we must update the Docker documentation attending to:

- [x] Update the hardware requirements.
- [x] Change the needed exposed ports.
- [x] Document step by step several scenarios: default, production and upgrade.
  - [x] Default (sample cluster)
  - [x] Production cluster
  - [x] Upgrade scenario (3.13 -> 4.0)

- [x] Modify the way that persistence work. (data volume -> multiple volumes)
- [x] Remove the service data volume section.
- [x] Explain the use of Open Distro for Elasticsearch integration.
- [x] Describe new environment variables. (https://github.com/wazuh/wazuh-docker/pull/322)
- [x] Enrich FAQ.

The new documentation must be clear and descriptive, taking into account the usability from the users' point of view. We must emphasize having a way of documenting that avoids future issues.

This issue is for tracking purposes, it might be updated frequently.

Regards

**Comment by xr09** [comment]
Default scenario is documented, it is designed to have a quick test of Wazuh with maximum ease. Default users and certificates are used in order to simplify the setup. This scenario will work with just cloning the repo and executing `docker-compose up`.

For the production deployment custom SSL certificates and users are strongly recommended, a sample config `production-cluster.yml` was provided on the wazuh-docker repo and this section will explain its usage.

**Comment by manuasir** [comment]
Related issue https://github.com/wazuh/wazuh-docker/issues/160

**Comment by xr09** [comment]
Fixed by #2890
