### ISSUE TITLE
OVA Virtual Machine 

### ISSUE THREAD

**Issue by kwilliams147** [wazuh/wazuh-documentation#309]
The link on the virtual machine doc doesn't work and says access denied. I do understand it is for testing and demo purposes.

https://documentation.wazuh.com/current/installation-guide/virtual-machine.html

**Comment by BraulioV** [comment]
Hi @kwilliams147,

there was an error in the documentation and as you said, the link doesn't work. This is already fixed in this PR #310, so it should appear in the doc very soon.

For now, you can download the OVA from here: https://packages.wazuh.com/vm/wazuh3.4.0_6.3.1.ova

Thanks for your feedback.

Regards,
Braulio.

**Comment by JuanjiJG** [comment]
Hello all,

This was already fixed thanks to @BraulioV, so I'll proceed to close this issue.

Regards,
Juanjo
