### ISSUE TITLE
Update 'Using Wazuh to monitor Microsoft Azure' documentation

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-documentation#3091]
Hi team,
This documentation is outdated and users are having a hard time to configure the Azure wodle to monitor Azure logs. The screenshots look different from the current interface.

For example, in this documentation: https://documentation.wazuh.com/4.0/azure/monitoring-services.html#using-azure-active-directory-graph. Note this screenshot:
![image](https://user-images.githubusercontent.com/30299229/97446892-3cd9dc00-192f-11eb-9312-3f127a8b970d.png)

This section now looks very different and it's hard to know what privileges we need to grant to the application:
![image](https://user-images.githubusercontent.com/30299229/97446955-53803300-192f-11eb-92a6-82e620b882d8.png)

This documentation needs a whole review.

Best regards,
Sergio.

**Comment by johnfont** [comment]
Hi team, i had to configure the Services monitoring in Azure recently and i took some screenshoots to help with this issue:

1. Creation of the application

In the `Azure Active Directory` section select the option `App registrations` and once inside, select `New registration`.

![imagen](https://user-images.githubusercontent.com/79602926/118054158-268bee80-b35c-11eb-9ffe-f9ad89c401d0.png)

1.2 - Proceed to `Register` our application:

![imagen](https://user-images.githubusercontent.com/79602926/118053372-c9436d80-b35a-11eb-9638-5374c49061e9.png)

2. Giving permissions to the application
 2.1 - Whether we have created a new application or are using an existing one, we need to access to the `Manage` Section in the application and select`API permissions` and `Add a permission`. 
![imagen](https://user-images.githubusercontent.com/79602926/118054725-2b9d6d80-b35d-11eb-9f52-83fdfc7bac4d.png)

`Select Microsoft APIs` > `Microsoft Graph`

![imagen](https://user-images.githubusercontent.com/79602926/118054896-7f0fbb80-b35d-11eb-83a2-8f7845b03a5b.png)

2.2 - Select `Delegated permissions`. Choose the permissions you want to provide to the application and click `Add permissions`

![imagen](https://user-images.githubusercontent.com/79602926/118056058-9485e500-b35f-11eb-9686-0029860ba61a.png)

![imagen](https://user-images.githubusercontent.com/79602926/118056163-cd25be80-b35f-11eb-8d65-28b61b775f67.png)

2.3 - In the Overview Section we can obtain the `Application ID`, a necessary field to authenticate the application later

![imagen](https://user-images.githubusercontent.com/79602926/118058564-d9f8e100-b364-11eb-973b-d7860a6e3f91.png)

3. Obtaining the application key for authentication

3.1 - Select `Certificates & secrets` and click in `New client secret` , then fill in the `DESCRIPTION `and `EXPIRES `fields and add the `client secret`. 

![imagen](https://user-images.githubusercontent.com/79602926/118056620-a7e58000-b360-11eb-9aa7-68173a4fa16b.png)


Once we add the key we will get its value. This will be the key with which we will authenticate our application in order to use the API.

![imagen](https://user-images.githubusercontent.com/79602926/118057173-b718fd80-b361-11eb-8930-19ba2e5cc003.png)

4. Giving access to our application to the Log Analytics API

4.1 - Finally, we must configure Log Analytics to ensure our access once we have authenticated ourselves in our application. First select the `Log Analytics workspace `entry. Next we will choose the workspace. In `Overview `we can see the `Workspace Id` field, which we will use to make requests to the API:

![imagen](https://user-images.githubusercontent.com/79602926/118058658-10cef700-b365-11eb-88a9-c64e7dd87240.png)

4.2 - Now select the `Access control (IAM)` input and choose the` add` option. In the add permissions window we will set the desired `role` and `select` our application, ending with the `save` option.

![imagen](https://user-images.githubusercontent.com/79602926/118058226-1a0b9400-b364-11eb-8cbe-d9ec8c7ba5d8.png)

Wazuh configuration

Next will see the options we have to configure for the Wazuh integration.

https://documentation.wazuh.com/4.0/azure/monitoring-activity.html#wazuh-configuration

Let me know if you need additional info.

Regards!

**Comment by CarlosRS9** [comment]
This documentation section was reviewed and updated in https://github.com/wazuh/wazuh-documentation/pull/4126. The suggested changes are already available in the `4.3` documentation.
