### ISSUE TITLE
Update dependency steps to install wazuh server on custom path

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#3584]
Hello, 

We should review and update the current documentation to install a Wazuh server in a custom path, the dependency steps are not currently working.

https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html

Regards,

David J. Iglesias

**Comment by mcarmona99** [comment]
### Issue status

Hi team,

The dependencies steps of the documentation should be deleted as there is no need to run the makefile with different deps when we want to install in a different path. 

If we want to install in a custom path, we just indicate it in the script `install.sh`. The problem is, when we do this step, wazuh is installed in the custom path, but python is installed in `/var/ossec.`

The current `framework Makefile` is hardcoding the path, as it can be seen here:

https://github.com/wazuh/wazuh/blob/6c817e9ae6d4d91bfbc6c3165befd04488a6e9bd/framework/Makefile#L8

We need to use `?=` instead of `=` to only declare the variable `PREFIX` if it hasn't been declared yet. In our case, the framework Makefile is always called from the installation script, so we could ommit this line. Using `?=` will have the same effect, but it will assign the default path in case we execute the Makefile from another place.

We also need to use `?=` in the `PREFIX` declaration in the `api Makefile` to avoid future errors.

After installing in a custom path with the change mentioned above, the following output appears when using `python3`:

`...python3: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory`

This happens because the library `libpython3.9.so.1.0` is not in /`wazuh/custom_path/lib/`.

The link from `/var/custom/framework/python/lib/libpython3.9.so.1.0` to `/wazuh/custom_path/lib/libpython3.9.so.1.0` isn't working. This link is done here (`src/Makefile`):

```
install_python:
	cd ${EXTERNAL_CPYTHON} && export WPATH_LIB=${PREFIX}/lib && export SOURCE_PATH=${ROUTE_PATH} && export WAZUH_FFI_PATH=${EXTERNAL_LIBFFI} && ${MAKE} install
	find ${WPYTHON_DIR} -name "*${WLIBPYTHON}" -exec ln -f {} ${PREFIX}/lib/${WLIBPYTHON} \;
```

After testing these lines, I have realized we are only executing `cd ${EXTERNAL_CPYTHON} && export WPATH_LIB=${PREFIX}/lib && export SOURCE_PATH=${ROUTE_PATH} && export WAZUH_FFI_PATH=${EXTERNAL_LIBFFI} && ${MAKE} install`. The second line isn't being executed (link to the missing library).
