### ISSUE TITLE
Replace "Elastic stack" by "Elastic Stack" in the documentation 

### ISSUE THREAD

**Issue by PilarQuesada** [wazuh/wazuh-documentation#4522]
Hello team. I have found some pages in the documentation where it is written "Elastic stack" instead of "Elastic Stack". 

Some of the pages where I have found this are:

- [Deploying with Kubernetes](https://documentation.wazuh.com/current/deploying-with-kubernetes/index.html?highlight=elastic%20stack)
- [Getting started](https://documentation.wazuh.com/current/user-manual/configuring-cluster/index.html?highlight=elastic%20stack)
- [Step-by-step installation](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/elastic-stack/all-in-one-deployment/all_in_one.html?highlight=stack)

However, I suggest doing a more extensive search to see if it is found elsewhere. 

I attach here also the screenshots: 

![Captura de pantalla 2021-11-08 a las 12 45 56](https://user-images.githubusercontent.com/72941768/140737526-776216a8-8e21-4020-b472-d306d79b3a75.png)
![Captura de pantalla 2021-11-08 a las 12 45 40](https://user-images.githubusercontent.com/72941768/140737528-a4cedd6e-f71b-446b-9c5f-9404c959f836.png)
![Captura de pantalla 2021-11-08 a las 12 46 05](https://user-images.githubusercontent.com/72941768/140737521-3629bd23-c79d-49fe-858b-f2fe484a04aa.png)
:

**Comment by Arcapas** [comment]
I creat the PR: [Correct Elastic Stack capitalization by Arcapas · Pull Request #4557](https://github.com/wazuh/wazuh-documentation/pull/4557)
There are some pages in the documentation where it is written "Elastic stack" instead of "Elastic Stack"
I create the branch 4522_4.2_elastic_stack_capitalization to make the corrections in the following files:
deploying-with-kubernetes.rst
configuring-cluster.rst
all_in_one.rst
wazuh-module-meta.rst
kubernetes-conf.rst
migrating-from-ossec.rst
elasticsearch-kibana-filebeat.rst
