### ISSUE TITLE
Outdated blog post on how to purge agents

### ISSUE THREAD

**Issue by arguellesm** [wazuh/wazuh-documentation#4559]
The blog post [How to purge non-active agents](https://wazuh.com/blog/how-to-purge-non-active-agents/) uses outdated links for the `/agents` endpoint and agent's life cycle documentation.

Examples should also be updated as `agents_list` is now a required field for the `DELETE /agents` query.

**Comment by javimed** [comment]
Wazuh 4.3+ docs now include a sub-section on [Removing disconnected agents](https://documentation.wazuh.com/current/user-manual/agents/remove-agents/restful-api-remove.html#removing-disconnected-agents).

Since this is an old blogpost, we added a note mentioning  the new documentation section for 4.3+ users.

We are closing this issue now though it can be re-opened to raise any points about this.

Thanks.
