### ISSUE TITLE
Update AWS integration's Trusted Advisor section

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh-documentation#4762]
# Description
The Trusted Advisor section of the documentation isn't updated with the latest changes to AWS. For example, the Kinesis' homepage is not the same:
The one shown in the Wazuh documentation:
![Wazuh documentation screenshot](https://user-images.githubusercontent.com/72474806/149799623-cf4a44e5-52fd-4215-891b-6c62867703cd.png)

Meanwhile, when browsing the AWS site this is the Kinesis' homepage that appears:
![AWS screenshot](https://user-images.githubusercontent.com/72474806/149799597-a54c1ad6-3e30-48bd-b19c-48e443cd1103.png)

Also, the CloudWatch section used to create a rule to forward data to Cloudwatch logs still uses CloudWatch Events, which has been deprecated in favor of Amazon Event Bridge.
The page that appears in the Wazuh documentation is the following:
![Wazuh documentation](https://user-images.githubusercontent.com/72474806/149800741-837b09b8-fcc6-445f-b46e-6253043a4705.png)

Meanwhile, AWS shows the following information.
![Amazon Event Bridge](https://user-images.githubusercontent.com/72474806/149800641-952f739e-896e-44fd-9c9d-40a9d4e1d1d4.png)

We should review **all the screenshots** along with the **configuration process** to make the integration easier to use for the end-user.

**Comment by CarlosRS9** [comment]
# Status update

We are working together with the marketing team to make sure that the new screenshots introduced in this section of the documentation conform to the parameters defined by them.

All the screenshots have had to be replaced, since the AWS interface has changed and the documentation was outdated. The text has also been changed as the steps to follow to implement this has been altered by AWS. CloudWatch is no longer used for event management but Amazon EventBridge is used instead.

**Comment by CarlosRS9** [comment]
# Status update

The following changes have been applied:

- All screenshots have been replaced.
- Updated the Trusted Advisor introduction paragraph.
- Added a diagram explaining the different AWS services used.
- Created a new section called `Amazon Kinesis configuration` which replaces the old `Amazon configuration`.
- Created a new section called `Amazon EventBridge configuration`.
- Updated the `Wazuh configuration` section explaining how to access the configuration from the UI
