### ISSUE TITLE
Add Filebeat and Wazuh dashboard keystore guides

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-documentation#4787]
Hello team!
I would like to recommend adding in the Installation Guide (and why not in the User Manual too) the creation of Filebeat and Kibana keystores to avoid having the usernames and passwords in plain text. For Instance:
```
opensearch.username: kibanaserver
opensearch.password: kibanaserver
```
This documentation can help you: https://www.elastic.co/guide/en/kibana/7.10/secure-settings.html
Setting a keystore in this way:
```
sudo -u wazuh-dashboard /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore create
sudo -u wazuh-dashboard /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore add <variable>
```
ie: _sudo -u wazuh-dashboard /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore add DASH_PASS_
The secret variables set in the keystore can be used in this way in the configuration file:
```
opensearch.username: {DASH_USER}
opensearch.password: {DASH_PASS}
```

The same thing for Filebeat: https://www.elastic.co/guide/en/beats/filebeat/7.10/keystore.html

I hope this information could be helpful.

**Comment by s-ocando** [comment]
Hi @dariommr, 

The new installation guide includes instructions to create the Filebeat keystore: [Configuring Filebeat](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#configuring-filebeat).

![image](https://user-images.githubusercontent.com/61882981/188658504-bf175295-1adb-4611-b239-e0cf4dc88559.png)

Initially, the default `admin:admin` credentials are set and are changed in the last step of the Wazuh dashboard installation: [Change the default Wazuh indexer credentials](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#change-the-default-wazuh-indexer-credentials). 

On the other hand, the OpenSearch dashboards keystore is configured by default in the Wazuh dashboard.

This way, both Filebeat and the Wazuh dashboard use keystores to store credentials rather than plain text. The Wazuh installation assistant use the same settings, and the password tool is adapted accordingly. 

I'm closing this issue, feel free to reopen it if necessary.
