### ISSUE TITLE
Vulnerabilities Providers 

### ISSUE THREAD

**Issue by Bouzeghoub** [wazuh/wazuh-documentation#4789]
Hi,
Please, I want add it in vulnerabilities Providers, could you tel me procedure for integration.

source/user-manual/capabilities/vulnerability-detection/offline-update.rst

Best regards.

**Comment by JcabreraC** [comment]
Hello @Bouzeghoub,

I am not being able to completely understand what your problem is. We currently support vulnerability scanning on ubuntu debian and redhat for Linux and Windows.

The default configuration extracts the information from the vendors directly, downloading the data needed for the scan. Optionally, you can define the path where you have these previously downloaded vendor files so that you don't have to connect to the internet to download this information.

To configure the parsing with local files, you must use the following tag:
```xml
<os path="/local_path/oval-definitions.xml">OS</os>
```
In the `ossec.conf` file.

Regards !

**Comment by JcabreraC** [comment]
Hello @Bouzeghoub 

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Juan
