### ISSUE TITLE
Add reparse option to CloudWatchLogs, Azure Storage and Google Cloud Storage documentation

### ISSUE THREAD

**Issue by robertogp21** [wazuh/wazuh-documentation#4902]
# Description

Currently CloudWatchLogs, Azure Storage and Google Cloud has a reparse option that provide the possibility of parsing older logs, and it is not included in the documentation .

For this issue, these services documentation must be updated.

**Comment by fdalmaup** [comment]
# Issue Update

Sections added to the `Considerations for configuration` page of the Azure and GCP prerequisites documentation. The `Reparse` section of the AWS prerequisites documentation was modified, removing the note that stated that the `--reparse` option was not available for CloudWatch Logs because it is already available since https://github.com/wazuh/wazuh/pull/12515
