### ISSUE TITLE
Suggestions to improve "Migrating to the Wazuh dashboard" document

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-documentation#5131]
As per work done with the manual test for "Migrating to the Wazuh dashboard" [#wazuh:13238](https://github.com/wazuh/wazuh/issues/13238), there are a few suggestions to improve the process documentation. Here you have the list of suggested changes. 

| Area| Guide step | Note |
|---|---|---|
|doc|step 2|NOTE 1 - Repo in documentation is wazuh_pre, so this step must be done. this must change for the final release to the main repo. - 🟠|
|doc|step 3|NOTE 2 - Note field on this point 3 should be updated to include a link to the migrate manager documentation. - 🟠|
|doc|step 3|NOTE 3 - Also, Should be updated or migrated to wazuh-indexer before this migration to wazuh-dashboard? - 🟠|
|doc|step 9|NOTE 4 - before uninstalling kibana we should verify deployment was fine and is working. Create a test step before uninstalling kibana. 🟠|
|doc|global|NOTE 5 - The migration process doesn't manage or inform about the custom or saved objects migration. Should be a note about how to address custom object migration. 🟠|

**Comment by s-ocando** [comment]
Note 1 - We were using the development repository for testing purposes. https://github.com/wazuh/wazuh-documentation/pull/5157 changes the links to production. 
Note 2, 3 and 4 are fixed in https://github.com/wazuh/wazuh-documentation/pull/5162.
Note 5 - Custom and saved objects are preserved during the migration process as they are stored in the Kibana index.
