### ISSUE TITLE
Wrong default values and missing settings for the Wazuh Dashboard configuration file

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-documentation#5500]
## Summary
Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/4349

During the review of the in-file documentation for the `wazuh.yml` file, the configuration file for the Wazuh Dashboard App, we have detected that some settings are completely missing in the web documentation, and others need to be updates as are using wrong default values.

#### Missing settings:
- checks.metaFields
- checks.timeFilter
- checks.maxBuckets
- extensions.hipaa
- extensions.nist
- extensions.tsc
- extensions.oscap
- extensions.gcp

> This setting allows hiding Wazuh for the specified roles. Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/3164
- disabled_roles

> Name for the sample alerts index
- alerts.sample.prefix

> [cron](https://g.co/kgs/Mh1TYS) related settings: these settings configure the behavior of background tasks performed by the App.
- cron.prefix
- cron.statistics.status
- cron.statistics.apis
- cron.statistics.interval
- cron.statistics.index.name
- cron.statistics.index.creation
- cron.statistics.shards
- cron.statistics.replicas

> These settings are used in the agents' enrollment interactive helper.
- enrollment.dns
- enrollment.password

> Custom logos
- customization.logo.app
- customization.logo.sidebar
- customization.logo.healthcheck
- customization.logo.reports

#### Outdated settings:
- wazuh-version.*: deprecated since 4.3.0. To be removed completely.
- api.selector: deprecated. To be removed.
- admin: seems to be no longer used. I assume it's been deprecated.
- timeout: default value is set to 8000. Actual value is 20000.
- wazuh.monitoring.shards: default value is set to 2. Actual value is 1.
- wazuh.monitoring.creation: default value is d (daily). Actual value is w (weekly).

**Comment by yenienserrano** [comment]
#### Missing settings:

- [ ]  checks.metaFields
- [ ]  checks.timeFilter
- [ ]  checks.maxBuckets
- [ ]  extensions.hipaa
- [ ]  extensions.nist
- [ ]  extensions.tsc
- [ ]  extensions.oscap
- [ ]  extensions.gcp

> This setting allows hiding Wazuh for the specified roles. Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/3164
- [ ]  disabled_roles

> Name for the sample alerts index
- [ ]  alerts.sample.prefix

> [cron](https://g.co/kgs/Mh1TYS) related settings: these settings configure the behavior of background tasks performed by the App.
- [ ]  cron.prefix
- [ ]  cron.statistics.status
- [ ]  cron.statistics.apis
- [ ]  cron.statistics.interval
- [ ]  cron.statistics.index.name
- [ ]  cron.statistics.index.creation
- [ ]  cron.statistics.shards
- [ ]  cron.statistics.replicas

> These settings are used in the agents' enrollment interactive helper.
- [ ]  enrollment.dns
- [ ]  enrollment.password

> Custom logos
- [ ]  customization.logo.app
- [ ]  customization.logo.sidebar
- [ ]  customization.logo.healthcheck
- [ ]  customization.logo.reports

#### Outdated settings:
- [ ]  wazuh-version.*: deprecated since 4.3.0. To be removed completely.
- [ ]  api.selector: deprecated. To be removed.
- [ ]  admin: seems to be no longer used. I assume it's been deprecated.
- [ ]  timeout: default value is set to 8000. Actual value is 20000.
- [ ]  wazuh.monitoring.shards: default value is set to 2. Actual value is 1.
- [ ]  wazuh.monitoring.creation: default value is d (daily). Actual value is w (weekly).
