### ISSUE TITLE
Azure integration configuration steps fail in the Create User example

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#5529]
Testing the Azure integration, we couldn't finish because one step in the documentation was not working. 
We started configuring Azure with this document: https://documentation.wazuh.com/current/azure/activity-services/services/log-analytics.html

The application was created, and the permissions were given and granted:
![image](https://user-images.githubusercontent.com/3830293/185636428-a657528e-1276-4056-b462-de56d40f84b4.png)

Client secret created:
![image](https://user-images.githubusercontent.com/3830293/185636634-bc7ce67e-3014-4361-abff-07368a2f0b11.png)

Log Analytics workspace created:
![image](https://user-images.githubusercontent.com/3830293/185636856-9dc7e515-9cec-4ec6-96c3-58b702b4ec3f.png)

IAM configured:
![image](https://user-images.githubusercontent.com/3830293/185637070-316d44d6-39f7-484c-9aa5-ecf94a818806.png)

But, after all, when we want to test with "Creating user" action, no logs appears with the query `AuditLogs`

**Comment by CarlosRS9** [comment]
This was because the documentation lacked a section explaining how to configure the Diagnostic Settings, which are the settings that are responsible for exporting the logs to a Log Analytics Workspace. We have opened https://github.com/wazuh/wazuh-documentation/pull/5562 to add this documentation and update the screenshots with the new Wazuh format and the Azure interface.

**Comment by alberpilot** [comment]
Great @CarlosRS9!
