### ISSUE TITLE
Review and update AWS WAF documentation

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-documentation#5808]
# Description

Our documentation indicates that WAF logs must be stored in S3 using Kinesis, but after reviewing the code it seems that the module itself would be compatible with WAF logs that have been stored in S3 directly by this service or in other ways.

It is necessary to confirm if we are really compatible with native logs, logs coming from Kinesis or both. It should also be clarified whether the module is compatible only with WAF classic or also with WAF v2. Once these points have been clarified, it will be necessary to update the documentation to make the conclusions clear.

On the other hand, the screenshots should be revised, as the screenshot in step 13 shows an example with GuardDuty instead of WAF and this could confuse our users.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>

For the completion of this issue we must ensure to check:

- [ ] Compatibility with WAF logs stored in S3 directly by the service or in other ways.
- [ ] Compatibility with WAF logs coming from Kinesis.
- [ ] Compatibility with WAF classic and WAF v2.
- [ ] Clarification of these points in the documentation.
- [ ] Revision of screenshots to ensure they are correct and not confusing.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>
After consulting with the team a different approach has been taken. Instead of setting up different WAFs, we will directly place sample WAF logs in S3 buckets manually and run the module to see if the integration runs correctly. We were still not successful in doing so, the configuration was initially set up like this but the parameters may not be configured properly.

```
<ossec_config>
	<wodle name="aws-s3">
	  <disabled>no</disabled>
	  <interval>10m</interval>
	  <run_on_start>yes</run_on_start>
	  <skip_on_error>yes</skip_on_error>
	  <bucket type="waf">
	    <name>wazuh-aws-wodle</name>       <!-- PUT HERE THE S3 BUCKET CHOSEN IN STEP 7 -->
	    <path>waf</path>                   <!-- PUT HERE THE PREFIX CHOSEN IN STEP 7 -->
	    <aws_profile>default</aws_profile>
	  </bucket>
	</wodle>
</ossec_config>
```

More testing and investigation remains.

**Comment by mateojames** [comment]
<h1> Issue Update </h1>

We were able to successfully process both logs from an AWS WAF Classic and AWS WAF V2, which were placed manually in a bucket.

<details><summary>Logs placed in the bucket</summary>

<img width="403" alt="image" src="https://user-images.githubusercontent.com/64434083/235240579-1e859de3-9676-4afb-9a4d-ef67ddd79f1f.png">

  <details><summary>AWS WAF Classic mock log used</summary>
  This logs were obtained from here: https://docs.aws.amazon.com/waf/latest/developerguide/classic-logging.html

   ``` 
  {"timestamp":1533689070589,"formatVersion":1,"webaclId":"385cb038-3a6f-4f2f-ac64-09ab912af590","terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","action":"ALLOW","httpSourceName":"CF","httpSourceId":"i-123","ruleGroupList":[{"ruleGroupId":"41f4eb08-4e1b-2985-92b5-e8abf434fad3","terminatingRule":null,"nonTerminatingMatchingRules":[{"action":"COUNT","ruleId":"4659b169-2083-4a91-bbd4-08851a9aaf74"}],"excludedRules":[{"exclusionType":"EXCLUDED_AS_COUNT","ruleId":"5432a230-0113-5b83-bbb2-89375c5bfa98"}]}],"rateBasedRuleList":[{"rateBasedRuleId":"7c968ef6-32ec-4fee-96cc-51198e412e7f","limitKey":"IP","maxRateAllowed":100},{"rateBasedRuleId":"462b169-2083-4a93-bbd4-08851a9aaf30","limitKey":"IP","maxRateAllowed":100}],"nonTerminatingMatchingRules":[{"action":"COUNT","ruleId":"4659b181-2011-4a91-bbd4-08851a9aaf52"}],"httpRequest":{"clientIp":"192.10.23.23","country":"US","headers":[{"name":"Host","value":"127.0.0.1:1989"},{"name":"User-Agent","value":"curl/7.51.2"},{"name":"Accept","value":"*/*"}],"uri":"REDACTED","args":"usernam=abc","httpVersion":"HTTP/1.1","httpMethod":"GET","requestId":"cloud front Request id"}}
  ```

  </details>

  <details><summary>AWS WAF V2 mock log used</summary>
  This logs were obtained from here: https://docs.aws.amazon.com/waf/latest/developerguide/logging-examples.html

   ``` 
{"timestamp":1576280412771,"formatVersion":1,"webaclId":"arn:aws:wafv2:ap-southeast-2:111122223333:regional/webacl/STMTest/1EXAMPLE-2ARN-3ARN-4ARN-123456EXAMPLE","terminatingRuleId":"STMTest_SQLi_XSS","terminatingRuleType":"REGULAR","action":"BLOCK","terminatingRuleMatchDetails":[{"conditionType":"SQL_INJECTION","sensitivityLevel":"HIGH","location":"HEADER","matchedData":["10","AND","1"]}],"httpSourceName":"-","httpSourceId":"-","ruleGroupList":[],"rateBasedRuleList":[],"nonTerminatingMatchingRules":[],"httpRequest":{"clientIp":"1.1.1.1","country":"AU","headers":[{"name":"Host","value":"localhost:1989"},{"name":"User-Agent","value":"curl/7.61.1"},{"name":"Accept","value":"*/*"},{"name":"x-stm-test","value":"10 AND 1=1"}],"uri":"/myUri","args":"","httpVersion":"HTTP/1.1","httpMethod":"GET","requestId":"rid"},"labels":[{"name":"value"}]}
  ```

  </details>

</details>

<details><summary>ossec.log</summary>

```
2023 Apr 28 19:38:59 wazuh-master->Wazuh-AWS {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "2023/04/28/AWSClassicLog", "s3bucket": "s3bucket"}, "timestamp": 1533689070589, "formatVersion": 1, "webaclId": "385cb038-3a6f-4f2f-ac64-09ab912af590", "terminatingRuleId": "Default_Action", "terminatingRuleType": "REGULAR", "action": "ALLOW", "httpSourceName": "CF", "httpSourceId": "i-123", "ruleGroupList": {"ruleGroupId": "41f4eb08-4e1b-2985-92b5-e8abf434fad3", "terminatingRule": null, "nonTerminatingMatchingRules": [{"action": "COUNT", "ruleId": "4659b169-2083-4a91-bbd4-08851a9aaf74"}], "excludedRules": [{"exclusionType": "EXCLUDED_AS_COUNT", "ruleId": "5432a230-0113-5b83-bbb2-89375c5bfa98"}]}, "rateBasedRuleList": [{"rateBasedRuleId": "7c968ef6-32ec-4fee-96cc-51198e412e7f", "limitKey": "IP", "maxRateAllowed": 100}, {"rateBasedRuleId": "462b169-2083-4a93-bbd4-08851a9aaf30", "limitKey": "IP", "maxRateAllowed": 100}], "nonTerminatingMatchingRules": {"action": "COUNT", "ruleId": "4659b181-2011-4a91-bbd4-08851a9aaf52"}, "httpRequest": {"clientIp": "192.10.23.23", "country": "US", "headers": {"Host": "127.0.0.1:1989", "User-Agent": "curl/7.51.2", "Accept": "*/*"}, "uri": "REDACTED", "args": "usernam=abc", "httpVersion": "HTTP/1.1", "httpMethod": "GET", "requestId": "cloud front Request id"}, "source": "waf"}}
2023 Apr 28 19:38:59 wazuh-master->Wazuh-AWS {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "2023/04/28/AWSV2Log", "s3bucket": "s3bucket"}, "timestamp": 1576280412771, "formatVersion": 1, "webaclId": "arn:aws:wafv2:ap-southeast-2:111122223333:regional/webacl/STMTest/1EXAMPLE-2ARN-3ARN-4ARN-123456EXAMPLE", "terminatingRuleId": "STMTest_SQLi_XSS", "terminatingRuleType": "REGULAR", "action": "BLOCK", "terminatingRuleMatchDetails": {"conditionType": "SQL_INJECTION", "sensitivityLevel": "HIGH", "location": "HEADER", "matchedData": ["10", "AND", "1"]}, "httpSourceName": "-", "httpSourceId": "-", "ruleGroupList": [], "rateBasedRuleList": [], "nonTerminatingMatchingRules": [], "httpRequest": {"clientIp": "1.1.1.1", "country": "AU", "headers": {"Host": "localhost:1989", "User-Agent": "curl/7.61.1", "Accept": "*/*"}, "uri": "/myUri", "args": "", "httpVersion": "HTTP/1.1", "httpMethod": "GET", "requestId": "rid"}, "labels": {"name": "value"}, "source": "waf"}}
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: +++ Debug mode on - Level: 2
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: +++ Table does not exist; create
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: +++ Marker: 2022/12/01
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: ++ Found new log: 2023/04/28/AWSClassicLog
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: ++ Found new log: 2023/04/28/AWSV2Log
2023 Apr 28 19:39:00 wazuh-master->aws-s3 DEBUG: +++ DB Maintenance
```

</details>

This is a first indication that the module is compatible with both types of logs. However, testing only only log from each does not assure full compatibility. It is to be defined if real WAFs should be created in order to test a more realistic environment and thus confirm the compatibility.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>

The team decided that real WAFs should be created in order to test a more realistic environment and thus confirm the compatibility properly.

The following components have been created:

- ACL (Access Control List)
- ABL (AWS Load Balance)
- EC2 instance

To have a working schema we:

1. Created a target group and added the Amazon EC2 instance as its target.
2. Configured a load balancer and a listener
3. Associated the web ACL with the ALB in AWS WAF.

The following step will be to configure rules in the WAF in order to later trigger them to generate logs. An example could be only allowing GET or POST requests, and sending a PUT request to trigger the log generation. The WAF also needs to be configured to send the logs directly into an S3 bucket instead of using Kinesis.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>

The rule mentioned in the last update was created, but differently to simplify the testing. The rule specifies that if a request of type GET or POST is detected, then this shall be blocked.

<details><summary>Dont-allow-HTTP-GET-and-POST Rule</summary>

```json
{
  "Name": "Dont-allow-HTTP-GET-and-POST",
  "Priority": 0,
  "Statement": {
    "OrStatement": {
      "Statements": [
        {
          "ByteMatchStatement": {
            "SearchString": "GET",
            "FieldToMatch": {
              "Method": {}
            },
            "TextTransformations": [
              {
                "Priority": 1,
                "Type": "NONE"
              }
            ],
            "PositionalConstraint": "EXACTLY"
          }
        },
        {
          "ByteMatchStatement": {
            "SearchString": "POST",
            "FieldToMatch": {
              "Method": {}
            },
            "TextTransformations": [
              {
                "Priority": 0,
                "Type": "NONE"
              }
            ],
            "PositionalConstraint": "EXACTLY"
          }
        }
      ]
    }
  },
  "Action": {
    "Block": {
      "CustomResponse": {
        "ResponseCode": 402,
        "CustomResponseBodyKey": "Not-allowed"
      }
    }
  },
  "VisibilityConfig": {
    "SampledRequestsEnabled": true,
    "CloudWatchMetricsEnabled": true,
    "MetricName": "Allow-only-HTTP-GET-and-POST"
  }
}
```

</details>

I have followed the documentation to test the functionality of the Load Balancer, but I am unable to reach it for some reason. I have checked the availability zone configuration, as well as the target group and security group configurations, but I am still unable to successfully make requests to the Load Balancer.

I have considered using the AWS CloudShell to make requests to the Load Balancer, but I do not have the necessary permissions to do so yet, I have request them after finding out. I have already set up an S3 bucket for logging, and as already mentioned, configured the rule in the WAF to block GET and POST requests. If we were to make a GET request to the default page of the Load Balancer, it should block the request and generate a log, which is what we are trying to achieve.

I suspect that the issue may be related to network connectivity or a misconfiguration, further investigation is needed.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>

The network connectivity has been reviewed and its seems it is not a problem related to availability areas.

Everything seems to be in its right place, except the ALB is reading the EC2 instance (for both ports 80 and 443) unhealthy, which makes sense as there is no service running in the EC2 on those ports.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/64434083/236312136-f8bffdfd-a9e9-4462-b136-e6ebcb852698.png">

However, theoretically this should not be an issue. The WAF should still block the request even before reaching the Load Balancer. After discussing with the team, we will set up an Apache inside the EC2 listening on ports 80 and optionally 443, to make sure that's not the problem.

The following checks must be done after setting up the Apache server:

1. Be able to reach the EC2 directly
2. Be able to reach the EC2 through the WAF (with all rules disabled) and the ALB
3. Repeat step 2 but add the mentioned rules. The request should be blocked and the logs should be generated.

**Comment by mateojames** [comment]
<h1> Issue Update </h1>

<h2>Summary</h2>

Following the instructions from the previous issue update, we were able to successfully generate logs by triggering a rule set up in a WAF, which were automatically stored in an S3 bucket. The problem had to do with the security groups, and the permission on both the Load Balancer and the EC2 to allow incoming traffic from port 80.

<h2>Description</h2>

An apache server was set up in the EC2 in port 80. After that, and after correctly setting the permissions, the healthcheck from the Target Group started working (_the 443 port target was removed_).

<img width="519" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/64434083/24729bea-8fae-4d72-b792-9aba6a4d962c">

We were then able to successfully "reach" the EC2 both directly and via the Load Balancer in port 80, where we could see Apaches default webpage.

<img width="1075" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/64434083/5f644ecb-688c-4f69-adc7-b211e7712c8c">

After that, following step 3, we set up the rule **Dont-allow-HTTP-GET-and-POST** Rule mentioned in a previous update, and generated a request. The WAF successfully blocked the request and returned the configured error message with a 402 status code we chose.

<img width="794" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/64434083/f9f58b76-ab7e-4439-896f-01dad2ddf01c">


After some minutes, the logs were correctly sent to the S3 bucket.

<details><summary>Log found in the S3</summary>

```json

{
  "timestamp": 1683645007758,
  "formatVersion": 1,
  "webaclId": "redacted",
  "terminatingRuleId": "Dont-allow-HTTP-GET-and-POST",
  "terminatingRuleType": "REGULAR",
  "action": "BLOCK",
  "terminatingRuleMatchDetails": [],
  "httpSourceName": "ALB",
  "httpSourceId": "redacted",
  "ruleGroupList": [],
  "rateBasedRuleList": [],
  "nonTerminatingMatchingRules": [],
  "requestHeadersInserted": null,
  "responseCodeSent": 402,
  "httpRequest": {
    "clientIp": "redacted",
    "country": "AR",
    "headers": [
      {
        "name": "User-Agent",
        "value": "PostmanRuntime/7.31.1"
      },
      {
        "name": "Accept",
        "value": "*/*"
      },
      {
        "name": "Postman-Token",
        "value": "16758264-7619-40b6-aa04-f59e1f5dd354"
      },
      {
        "name": "Host",
        "value": "redacted.amazonaws.com"
      },
      {
        "name": "Accept-Encoding",
        "value": "gzip, deflate, br"
      },
      {
        "name": "Connection",
        "value": "keep-alive"
      }
    ],
    "uri": "/",
    "args": "",
    "httpVersion": "HTTP/1.1",
    "httpMethod": "GET",
    "requestId": "1-645a624f-77d036260d64790e642b01f8"
  }
}

```

</details>

This is a good advancement, and the remaining testing is rather simple: We will connect a Wazuh Manager to the AWS WAF bucket, which will consume its logs. We will then be able to confirm it is parsing them correctly by the logs in the Manager. This test has been done with a WAFv2. The following step is to replace it with a WAF classic, and the process will be repeated.

**Comment by mateojames** [comment]
<h1>Issue Update</h1>

After reading the documentation, and by comparing an implementation done with Kinesis and an implementation without it, we have found a discrepancy in the logs paths.

<h2>Logs path structure</h2>

<h3>Current documentation (WAF logging using Kinesis):</h3>

`<bucket_name>/<prefix>/<year>/<month>/<day>/<hh>`


<h3>Tested implementation (WAF logging directly to S3):</h3>

![image](https://github.com/wazuh/wazuh-documentation/assets/64434083/13f17894-b433-43c8-a9e0-ef49d53aebf3)

Formatted:

`<bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/WAFLogs/<region>/<waf_name>/<year>/<month>/<day>/<hh>/<mm>`


<h1>Conclusion</h1>

The logs have a different path when logging directly into an S3 rather than through Kinesis, as the current implementation supports. **This means that the module itself is not compatible with WAF logs that have been stored in S3 directly by this service.**

A development could be made in the future in order to gain compatibility with the different path structure. In that case, once the module is compatible, the logs could be tested to see if there is a difference in the formatting. But concerning this documentation issue, we can declare it closed.

**Comment by EduLeon12** [comment]
## Review 

The issue was well addressed with effective troubleshooting and a understanding conclusion. Also, @mateojames identified a future improvement regarding log paths. Overall, the resolution fulfills the problem statement, making this issue satisfactorily resolved. 

Looks Good To Me (LGTM)!

**Comment by aradkdj** [comment]
# Review

The approach and troubleshooting was effective, the conclusion understandable, and  this issue seems to be resolved.

Looks Good To Me (LGTM)!
