### ISSUE TITLE
macOS ULS logs - No mention of `log`'s syslog compatibility mode

### ISSUE THREAD

**Issue by kujo-jotaro** [wazuh/wazuh-documentation#5847]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-alpha2 | wazuh-logcollector | Agent | [Installation guide](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html) | macOS Monterey |

## Description

As noted by @jnasselle's [comment](https://github.com/wazuh/wazuh/issues/15771#issuecomment-1366104815), wazuh-agent utilizes macOS's `log` tool with the flag `--style syslog` in order to comply with wazuh-analysisd. This isn't mentioned anywhere in the [macOS log collection documentation](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-macoslogs.html), and it could become a hindrance should anyone try to write their own decoders and ruleset for this platform.

The proposition is adding these details to the documentation, maybe under [this](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html) section.

**Comment by javimed** [comment]
Although some mentions are already present,

![imagen](https://user-images.githubusercontent.com/47069802/210103057-40ca282f-994d-492f-8ff0-cf1db8e602f9.png)

![imagen](https://user-images.githubusercontent.com/47069802/210103035-77b0f88f-7b50-4de8-ac20-5ef4bc9c41e0.png)

the section referred in this issue is indeed in need of a mention to it.
