### ISSUE TITLE
Update Wazuh's portal TCP port

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-documentation#5854]
Testing [Deployment with Ansible](https://github.com/wazuh/wazuh/issues/15768), the documentation says that the portal should be accesible from port 5601, [but it is accesible by the HTTPS default port (443)](https://github.com/wazuh/wazuh/issues/15768#issuecomment-1366760607).

The port should be updated to 443 (HTTPS) in the documentation.

**Comment by alberpilot** [comment]
This issue refers to the section: https://documentation-dev.wazuh.com/v4.4.0-alpha2/deployment-options/deploying-with-ansible/guide/install-wazuh-manager.html. This other one: https://documentation-dev.wazuh.com/v4.4.0-alpha2/deployment-options/deploying-with-ansible/guide/install-indexer-dashboard.html has not the note and maybe it should. I understand that the note was included at the Wazuh manager level because it will be possible to see alerts. On the other hand, it's not intuitive to have the note about the dashboard access in the Wazuh manager section (IMO). 

Indeed, port 5601 is incorrect in the first mentioned link and this one: https://documentation-dev.wazuh.com/v4.4.0-alpha2/deployment-options/deploying-with-ansible/reference.html.
