### ISSUE TITLE
Description of result fields in the API reference

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#650]
Hi team,

It would be helpful if we include a list with a description of the default parameters in the result of the API calls.

Sometimes it is complicated to know what information refers a field in the response.

Kind regards,
Miguel

**Comment by JuanjiJG** [comment]
Hello @migruiz4,

Thank you for your suggestion, it's really interesting.

I've moved your proposal to [this issue](https://github.com/wazuh/wazuh-api/issues/199) on the Wazuh API repository because it's the component that would need to be updated in order to improve the documentation. The Wazuh API team will investigate about this.

I'll proceed to close this issue.

Regards,
Juanjo
