### ISSUE TITLE
Source field is not supported for centOS regarding syscollector packages fields

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#6600]
### Description

Syscollector `source` field is not present for rpm system although is included in the availability column

![image](https://github.com/wazuh/wazuh-documentation/assets/11089305/30721bd3-b470-4b8b-bede-6274a8334906)

**Documentation page**: https://documentation.wazuh.com/current/user-manual/capabilities/system-inventory/available-inventory-fields.html

**Comment by MiguelazoDS** [comment]
# Brief analysis 

The RPM package information is obtained mainly from the RPM library for RPM versions newer than 4.16. Otherwise from Berkeley DB. In case none of the previous options are available, a fallback method using the rpm command line tool is performed. 

Using the RPM library we can see in the code that the source information is being parsed
https://github.com/wazuh/wazuh/blob/master/src/data_provider/src/packages/rpmPackageManager.cpp#L163

but the information seems to be missing. 

<details><summary> Expand </summary>

![2023-10-10_10-52_1](https://github.com/wazuh/wazuh-documentation/assets/13010397/2834ebdf-fef3-487e-838f-3fb37f16d6de)
The source info is an empty string
![2023-10-10_10-52](https://github.com/wazuh/wazuh-documentation/assets/13010397/16cba073-70b3-4901-802c-d42c734e9b3f)

</details>
