### ISSUE TITLE
Improve Wazuh RBAC Use case instructions

### ISSUE THREAD

**Issue by JorgeMarinoDev** [wazuh/wazuh-documentation#6893]
## Description

Improve instructions in [RBAC Use case: Give a user permissions to read and manage a group of agents](https://documentation-dev.wazuh.com/v4.7.2-rc1/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents).

Inside [Mapping with Wazuh](https://documentation-dev.wazuh.com/v4.7.2-rc1/user-manual/user-administration/rbac.html#mapping-with-wazuh) at **Step 7. Click Create Role mapping and complete the empty fields with the requested information.**

There is this instruction

Roles: Select the role created previously and the cluster_readonly role. This role assigns the user basic configuration reading permissions.

**Request**
After performing E2E RBAC tests, we found that this step is easy to overlook.

**Please reword and include Team_A_Role** along with **cluster_readonly**. Simply following the example above in the doc.

**Comment by GGP1** [comment]
## Update

The documentation refers to *"Select the role created previously"* because the instructions do not specify a name for the role. The image showcases a role called `Team_A_role` but that may not be what the users choose, so applying the change suggested would be confusing for them.

I added a clarification to avoid the overlooking mentioned in this issue while not affecting the ones that use a custom name.
