### ISSUE TITLE
Syscollector hotfixes undocumented

### ISSUE THREAD

**Issue by juresaht2** [wazuh/wazuh-documentation#6990]
According to [Configuring vulnerability detection](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst) there is a `<hotfixes>` option for `syscollector`, which is never mentioend in the documentation:
[System inventory > Configuration](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/system-inventory/configuration.rst)

According to some random google searches, it seems it's only available on Windows, but perhaps this should be checked with a more reliable source.

**Comment by rauldpm** [comment]
Hello

Indeed, reviewing the documentation, the `syscollector` hotfixes option is not mentioned in https://documentation.wazuh.com/current/user-manual/capabilities/system-inventory/configuration.html, and in principle, it should be mentioned at least, since it is exclusive to Windows

It is mentioned however in https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html as an available option

![image](https://github.com/wazuh/wazuh-documentation/assets/14913942/2b2f224a-1fa9-432f-b60e-05e8185267c5)


Keep in mind that the links you have provided correspond to the master branch, which does not correspond to the latest production version but rather to the latest available development.

That said, I am going to add the issue to the team so that it can be triaged and worked on if deemed appropriate, thank you!

**Comment by juresaht2** [comment]
Yes, I assumed that any changes would be based off the latest development version.

I'm using 4.4.4 , so the changes will not help me, but perhaps they will help others. :)
