### ISSUE TITLE
Kibana plugin install-proxy

### ISSUE THREAD

**Issue by Nymeria1** [wazuh/wazuh-documentation#74]
Hi,
Following the documentation I install the Wazuh App plugin for Kibana with the comand below:

`$ /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip`

but unfortunately I obtain this error: 

`Error: Client request error: connect EHOSTUNREACH 54.230.128.120:443
Plugin installation was unsuccessful due to error "Client request error: connect EHOSTUNREACH 54.230.128.120:443"`

So I have tried the local installation. 
After the download with the command:

` /usr/share/kibana/bin/kibana-plugin install wazuhapp url file:///tmp/wazuhapp.zip` 

I have this also error:

`Attempting to transfer from wazuhapp
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/wazuhapp/wazuhapp-5.5.2.zip
Error: Client request error: connect ETIMEDOUT 54.243.108.41:443
Plugin installation was unsuccessful due to error "Client request error: connect ETIMEDOUT 54.243.108.41:443"`

Could you have any suggestion to install the plugin with proxy? Many thanks.

**Comment by malbarral** [comment]
Hello @Nymeria1,

Please, make sure that you are running exactly this command: `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip`. If it doesn't work, try `/usr/share/kibana/bin/kibana-plugin install http://packages.wazuh.com/wazuhapp/wazuhapp.zip`.

It is weird, because the host should be "packages.wazuh.com", not "54.230.128.120:443", do you have some special configuration in your system?

When you tried the local installation, it was wrong. The correct command is `/usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuhapp.zip`. If you install the App this way, take into account that the Wazuh App package has to be manually generated.

Best regards,
Manuel

**Comment by Nymeria1** [comment]
Great suggestion!
Local installation worked with your command.
Thanks :)

Best regards,
