### ISSUE TITLE
Improve AWS Security Hub Documentation

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-documentation#7588]
## Description

While working on [Release 4.9.0 - Alpha 3 - E2E UX tests - Amazon Security Hub #24869](https://github.com/wazuh/wazuh/issues/24869), provided documentation for 4.9.0-alpha3 on configuring and setting AWS Security Hub presented a great deal of troubles, inhibiting from successfully implementing the configuration and thus allowing to pass the test successfully.

The document seems to be focused on experienced AWS users, where many concepts are assumed to be known, and many links to AWS documentation are provided, generating a lot of effort to accomplish a simple task that would be easier to configure if examples were provided.

It would be a lot easier for any user if the documentation provided examples and eventually references other documentation to learn more on the subject, but not to implement the feature itself.

Discarding regex option was not even possible to be tested since no event generation procedure was available (this might be a documentation or E2E design issue).

More details are provided in the [Feedback ](https://documentation-dev.wazuh.com/v4.9.0-alpha3/cloud-security/amazon/services/supported-services/security-hub.html)section of the E2E issue, as well as in the comments.

**Comment by nico-stefani** [comment]
# Update

I've been reviewing the documentation section and I noted some items that we could improve.

These are the suggestions:

* Add a diagram showing the AWS architecture, for this use case, and how are the interactions with Wazuh
* Highlight the pre-requisites section https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L35
* Include the IAM policies as a code block https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L49-L50
* Give more relevance to the EventBridge configuration section https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L73-L82
* Include the configurations examples directly instead of pointing to WAF https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L84
* Include a link to the SQS creation page and maybe add some images of the procedure https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L86-L117
* Include images for the *S3 and Event Notifications* section https://github.com/wazuh/wazuh-documentation/blob/31663276a0af97ac4fae367460c5c0c3a51f3d64/source/cloud-security/amazon/services/supported-services/security-hub.rst?plain=1#L119-L128

Before implementing these items I'll put them in common with the documentation team to get feedback from them.

**Comment by nico-stefani** [comment]
# Update

After discussing the proposed items we decide to continue with:

* Include the IAM policies as a code block
* Move the EventBridge explanation to the introduction section
* Explain what to find in the WAF link
* Add screenshots for the SQS procedure
* Add screenshots for the S3 procedure
