### ISSUE TITLE
File integrity monitoring

### ISSUE THREAD

**Issue by Nymeria1** [wazuh/wazuh-documentation#76]
Hi guys :)
With your help I correctly added the new agent. Now, via Wazuh agent manager in windows I have added the folder to monitor like follow:
`<syscheck> [...] <!-- My test. --> <directories check_all="yes" realtime="yes" report_changes="yes" alert_new_files="yes">/test</directories></syscheck>`

But when I create a new file in that directory no logs appears in wazuh-alert index.

Many thanks

**Comment by snaow** [comment]
Hi @Nymeria1,

I am glad you added a new agent.
Please, do you mind to open again your Syscheck configuration question in Wazuh mailing list?
This repository is dedicated to Wazuh Documentation and your issue seems not related to the docs.

[Wazuh mailing list ](https://groups.google.com/forum/#!forum/wazuh)

PS: alert_new_files flag can't be set in <directories> entry. Check reference [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html)

Thanks,
Pedro.
