### ISSUE TITLE
Using password for authentication has outdated log reference

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-documentation#7718]
## Description
A user reported [here](https://github.com/wazuh/community/issues/33734) that the `grep "Random password" /var/ossec/logs/ossec.log` is not returning anything after applying the changes of the `Prerequisites` section of [this documentation](https://documentation.wazuh.com/current/user-manual/agent/agent-enrollment/security-options/using-password-authentication.html#prerequisites).

I validated and the current message is this one:
`2024/08/29 15:55:55 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass`

So, the command used to get the log should be updated.

**Comment by Dwordcito** [comment]
@wazuh/devel-cppserver-div1 

Check the logic in: wazuh/src/os_auth/main-server.c

**Comment by MiguelazoDS** [comment]
I don't see what is the issue here. Following the steps mentioned in the documentation https://documentation.wazuh.com/current/user-manual/agent/agent-enrollment/security-options/using-password-authentication.html#prerequisites

I get this 

![image](https://github.com/user-attachments/assets/323ec67a-4d71-4830-8896-8990724a3479)

Of course, if you set the password beforehand you will get the other message, where the password is specified in the file

![image](https://github.com/user-attachments/assets/ddd802f9-4093-4675-bd6c-55f5e020ddc5)

**Comment by sebasfalcone** [comment]
## Continuation
@MiguelazoDS Lets update the user with this information

@Dwordcito This issue can be closed and continued on the community thread
