### ISSUE TITLE
Raspbian OS support on x86

### ISSUE THREAD

**Issue by vnasser** [wazuh/wazuh-documentation#7785]
Curios How Raspbian is supported on x86?
Also when will the central components be supported on ARM?
![wazuh1](https://github.com/user-attachments/assets/3d03f7e4-fa59-4e76-9cd1-7fb04d7a27eb)

**Comment by vikman90** [comment]
@vnasser this is clearly a wrong entry in the packages list.

It's caused by:
- https://github.com/wazuh/wazuh-documentation/pull/6823

Current version 4.9.0 of the manager is not provided for Raspbian or Debian on ARM. In fact, we're working to provide back the manager on ARM in 4.9.1. The rest of central components might be supported on ARM as of 4.10.x, but we don't have an accurate date yet.

I'm going to use this issue to review the supported versions and propose a change if I find any errors.

Thank you very much for reporting this problem.

Best.

**Comment by vnasser** [comment]
Awesome.
please let me know how i can help.

All the best,
-*victor*
