### ISSUE TITLE
Wrong selected section when clicking on links

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#866]
Hi,

I just realized that the selection of the current page in the left menu doesn't work when accessing to them by links:

![image](https://user-images.githubusercontent.com/10210567/51913976-0aa4ee80-23d8-11e9-82f6-2705f6c75491.png)

And after clicking the link:
![image](https://user-images.githubusercontent.com/10210567/51914023-26a89000-23d8-11e9-83dd-ecbfe8e16945.png)

Cheers

**Comment by JaoChaos** [comment]
Deprecated the idea that this issue is related to the design part of the doc.
The main problem is in the .rst code.
When a link is referenced using the :ref: label, the CSS does not charge the background nav block.

Working on fixing this issue @manuasir.

Thanks for your help.

Regards, 
Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
When testing changes on a local deploy of the doc, I see that bug does not happen in local, only in the official deployed version.
Still working on it.

**Comment by JaoChaos** [comment]
Hi team:

This problem can't be fixed.
Basically, when you choose to move to a source into the documentation, the page does not charge the page; indeed charges the section.
Let me explain:

If we are in this page -> (https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html) the section in the left column marks as it should because that page has been charged.
But if we move to the (https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html#installing-wazuh-api) which is a section inside that page, the left column won't mark it because that last href to move to that section is not in the column.

So there is only 1 option: Place in the left column EVERY section in the doc (which is not viable because it will be infinite scrolling).

So personally, I think that this is "probably" impossible to solve.

Best regards, 

Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
I finally found the bug:

When an internal URL is referenced in the code using :ref: it is generated later as an anchor of the URL:

https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html#installing-wazuh-manager

The #installing-wazuh-manager part is what causes the section to not charge the css in the left navbar.
