### ISSUE TITLE
'Protect your ELK'/'Protect your Installation' section

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#997]
Hi team,

A lot of users have been asking us about how to improve the Security of their ELK Stack.

We already have information about how to configure SearchGuard and X-Pack, but they are spread along the Documentation menu.

![imagen](https://user-images.githubusercontent.com/37381070/53956795-e4602600-40dc-11e9-9743-24e64a6d25b2.png)

![imagen](https://user-images.githubusercontent.com/37381070/53956700-9cd99a00-40dc-11e9-8f51-0d0fa1403635.png)

I suggest grouping all these configurations under 

- 'Installation Guide' >
     - 'Protect your Installation' >           
          - 'Protecting the Wazuh API '
          - 'Protecting Filebeat - Logstash'
          - 'Protecting your Elasticsearch & Kibana'

I suggest also adding the different security levels to the 'Protect your Elasticsearch & Kibana' section, with the following 3 levels.

### Level 1 - Using NGINX

Characteristics:
- HTTP Basic Authorization for Kibana
- Transport Layer Encryption between browser and Kibana server
- No Role Based Auth
- Easy to configure

### Level 2 - Using SearchGuard Community Version (Free) or X-Pack Security (Paid)

Characteristics:
- Authorization for Elasticsearch API & Kibana
- Role Based Auth (Index Level)
- Transport Layer Encryption between browser and Kibana server
- Transport Layer Encryption between Logstash and Elasticsearch
- Audit Security Events
### Level 3 - Using SearchGuard Enterprise (Paid) or X-Pack Security (Paid)

Characteristics:
- Same from previous level
- Role Based Auth (Document Level)
- Integration with LDAP, Active Directory, Kerberos, SAML

**Comment by JaoChaos** [comment]
Hi @migruiz4,
thanks for your contribution.
I am studying this purpose and it will be done ASAP.

Best regards,

Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
The actual structure is as follows:
- Protect your installation.
  - 'Protecting the Wazuh API '
  - 'Protecting Filebeat - Logstash'
  - 'Protecting your Elasticsearch & Kibana'
  - Using searchguard
  - Using X-Pack

I've decided to don't mix the searchguard section with the Elastic section as proposed in the issue because it ends up in a section extremely long and hard to read, and as in the searchguard section it is also explained further things as using it with Logstash and filebeat, it is better to let it apart from the Elastic section.
Same thing with X-Pack.

**Comment by jesusgn90** [comment]
Update https://github.com/wazuh/wazuh-kibana-app/issues/1433#issuecomment-491891800

**Comment by jesusgn90** [comment]
Included inhttps://github.com/wazuh/wazuh-documentation/tree/elastic-7
